name: C/C++ CI

on:
  push:
    branches: [ "main", "feat/*", "fix/*" ]
  pull_request:
    branches: [ "main", "feat/*", "fix/*"  ]
  schedule:
  - cron: "0 3 * * 1"
  
jobs:
  build:
    name: make testing
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install libdev
      - run: make
      
      
      
